title: Dreadnaught Engine Devlog
description: Building a custom C++23 Data-Oriented game engine.
theme: jekyll-theme-hacker
paginate: 10
paginate_path: "/devlog/page:num/"
plugins:
  - jekyll-paginate
collections:
  notes:
    output: true
